In [2]:
import torch
import numpy
x = torch.arange(12)
print(x)
x.shape
x.numel()
x = x.reshape(3,4)
print(x)
x = x.reshape(3,-1)
print(x)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
12


In [3]:
print(torch.zeros((2, 3, 4)))
print(torch.ones((2, 3, 4)))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
print(torch.randn(3, 4))
print(torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]))

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
print(torch.exp(x))

In [ ]:
#对多个张量按照指定轴方向连接
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))
print(torch.cat((X, Y),dim=1))
print(X == Y)
#对张量中的所有元素进行求和，会产生一个单元素张量。
print(X.sum())
print(X[-1])
print(X[1:3])
X[1, 2] = 9
print(X)
X[0:2, :] = 12
print(X)

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a+b)

In [ ]:
#运行一些操作可能会导致为新结果分配内存
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
before = id(Y)
print(before)
Y = Y + X
print(id(Y))
id(Y) == before

In [ ]:
#们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
#使用zeros_like来分配一个与Y形状相同的全0的块
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
#如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before

In [ ]:
import numpy
A = X.numpy()
B = torch.tensor(A)
print(A)
print(B)
type(A), type(B)

In [ ]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)